datalocker/urls.py
### Copyright 2015 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved.###

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

from datalocker import views


app_name = 'datalocker'
urlpatterns = [
    path('noaccess',
         views.no_access,
         name='no_access'),

    path('login',
         auth_views.LoginView.as_view(),
         name='app_login'),
    path('logout',
         auth_views.LogoutView.as_view(),
         name='app_logout'),
    path('password_change',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('submission',
         views.form_submission_view,
         name='form_submission'),

    path('users',
         views.users_list,
         name='users_list'),

    path('<int:locker_id>/archive',
         views.locker_archive,
         name='locker_archive'),
    path('<int:locker_id>/modify',
         views.modify_locker,
         name='modify_locker'),
    path('<int:locker_id>/unarchive',
         views.locker_unarchive,
         name='locker_unarchive'),

    path('<int:locker_id>/submissions/add',
         views.submission_add,
         name='submission_add'),
    path('<int:locker_id>/submissions/<int:submission_id>/delete',
         views.submission_delete,
         name='submission_delete'),
    path('<int:locker_id>/submissions/<int:submission_id>/discussion/add',
         views.comment_add,
         name='comment_add'),
    path('<int:locker_id>/submissions/<int:submission_id>/discussion/modify',
         views.comment_modify,
         name='comment_modify'),
    path('<int:locker_id>/submissions/<int:submission_id>/discussion',
         views.comments_list,
         name='comments_list'),
    path('<int:locker_id>/submissions/<int:submission_id>/undelete',
         views.submission_undelete,
         name='submission_undelete'),
    path('<int:locker_id>/submissions/<int:submission_id>/workflow/modify',
         views.workflow_modify,
         name='workflow_modify'),
    path('<int:locker_id>/submissions/<int:submission_id>',
         views.submission_view,
         name='submission_view'),
    path('<int:locker_id>/submissions',
         views.submissions_list_view,
         name='submissions_list'),

    path('<int:locker_id>/users',
         views.locker_users,
         name='locker_users'),
    path('<int:locker_id>/users/add',
         views.locker_user_add,
         name='locker_user_add'),
    path('<int:locker_id>/users/delete',
         views.locker_user_delete,
         name='locker_user_delete'),

    path('',
         views.locker_list_view,
         name='index'),
]

if settings.DEBUG:
    urlpatterns += [
        path('testing/400',
             views.testing_bad_request_view,
             name='testing_bad_request'),
        path('testing/403',
             views.testing_forbidden_view,
             name='testing_forbidden'),
        path('testing/404',
             views.testing_not_found_view,
             name='testing_not_found'),
        path('testing/500',
             views.testing_server_error_view,
             name='testing_server_error'),
    ]

##
# EXAMPLE Urls
#
# /datalocker
# /datalocker/#/submissions
# /datalocker/#/submissions/#/view
# /datalocker/#/settings
# /datalocker/#/submissions/#/comments

datalocker/templates/datalocker/main_template.html
{# Copyright 2015 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved. #}
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title-wrapper %}
      <title>
        {% block page-meta-title %}Site{% endblock page-meta-title %}
        :: {% block page-meta-org %}Data Locker{% endblock page-meta-org %}
      </title>
    {% endblock title-wrapper %}

    {% block favicons %}
      <link rel="apple-touch-icon" sizes="57x57"
            href="{% static 'datalocker/img/apple-icon-57x57.png' %}" />
      <link rel="apple-touch-icon" sizes="60x60"
            href="{% static 'datalocker/img/apple-icon-60x60.png' %}" />
      <link rel="apple-touch-icon" sizes="72x72"
            href="{% static 'datalocker/img/apple-icon-72x72.png' %}" />
      <link rel="apple-touch-icon" sizes="76x76"
            href="{% static 'datalocker/img/apple-icon-76x76.png' %}" />
      <link rel="apple-touch-icon" sizes="114x114"
            href="{% static 'datalocker/img/apple-icon-114x114.png' %}" />
      <link rel="apple-touch-icon" sizes="120x120"
            href="{% static 'datalocker/img/apple-icon-120x120.png' %}" />
      <link rel="apple-touch-icon" sizes="144x144"
            href="{% static 'datalocker/img/apple-icon-144x144.png' %}" />
      <link rel="apple-touch-icon" sizes="152x152"
            href="{% static 'datalocker/img/apple-icon-152x152.png' %}" />
      <link rel="apple-touch-icon" sizes="180x180"
            href="{% static 'datalocker/img/apple-icon-180x180.png' %}" />
      <link rel="icon" type="image/png" sizes="192x192"
            href="{% static 'datalocker/img/android-icon-192x192.png' %}" />
      <link rel="icon" type="image/png" sizes="32x32"
            href="{% static 'datalocker/img/favicon-32x32.png' %}" />
      <link rel="icon" type="image/png" sizes="96x96"
            href="{% static 'datalocker/img/favicon-96x96.png' %}" />
      <link rel="icon" type="image/png" sizes="16x16"
            href="{% static 'datalocker/img/favicon-16x16.png' %}" />
      <link rel="manifest"
            href="{% static 'datalocker/img/manifest.json' %}" />
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta name="msapplication-TileImage"
            content="{% static 'datalocker/img/ms-icon-144x144.png' %}" />
      <meta name="theme-color" content="#ffffff" />
      <link rel="shortcut icon" type="image/x-icon"
            href="{% static 'datalocker/img/favicon.ico' %}" />
    {% endblock favicons %}

    {% block site-styles %}
      <link type="text/css" rel="stylesheet"
            href="{% static 'datalocker/css/bootstrap-3.3.5.min.css' %}" />
      <link type="{text/css" rel="stylesheet"
            href="{% static 'datalocker/css/tablesorter.css' %}" />
      <link type="text/css" rel="stylesheet"
            href="{% static 'datalocker/css/datalocker.css' %}" />
    {% endblock site-styles %}
  </head>

  {% block body-tag %}<body>{% endblock body-tag %}
    {% block header-wrapper %}
      <header class="hidden-print">
        {% block header-top %}{% endblock %}
        {% block header-navbar %}
          <div class="document-header">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button"
                          class="navbar-toggle collapsed"
                          data-toggle="collapse"
                          data-target="#bs-example-navbar-collapse-1"
                          aria-expanded="false"
                          >
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'datalocker:index' %}"
                     ><span class="application-name" id="application-name">
                      {% block app-name %}Data Locker{% endblock app-name %}
                    <span class="sr-only">Homepage</span></span>
                  </a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  {% block personal-bar-wrapper %}
                    <ul class="nav navbar-nav navbar-right personal-bar">
                      {% if request.user.is_authenticated %}
                        <li class="dropdown">
                          <a href="#"
                             class="dropdown-toggle"
                             data-toggle="dropdown"
                             id="dropdown-personal-bar"
                             role="button"
                             aria-haspopup="true"
                             aria-expanded="false"
                             >
                            <span class="sr-only">
                              Currently logged in username:
                            </span>
                            <span id="current-username"
                                  >{{ request.user.username }}</span>
                            <span class="caret"></span>
                          </a>
                          <ul aria-label="site-wide commands for the current user"
                              class="dropdown-menu pull-right"
                              role="menu">
                            {% include "datalocker/personalbar-menu.html" %}
                          </ul>
                        </li>

                      {% else %}
                        <li>
                          <a href="{% block login-url %}{% url 'datalocker:app_login' %}{% endblock %}"
                             >{% block login-label %}Log In{% endblock login-label %}</a>
                        </li>
                      {% endif %}
                    </ul>
                  {% endblock personal-bar-wrapper %}
                </div>{# /.navbar-collapse #}
              </div>{# /.container-fluid #}
            </nav>
          </div>
        {% endblock header-navbar %}
        {% block breadcrumbs %}
          <div class="document-breadcrumbs hidden-print">
            <span class="document-breadcrumbs-label">
              You are here:
            </span>
            <ol class="breadcrumb-trail">
              {% block breadcrumb-trail %}
              {% endblock breadcrumb-trail %}
            </ol>
          </div>
        {% endblock breadcrumbs %}
        {% block header-bottom %}{% endblock %}
      </header>
    {% endblock header-wrapper %}

    <div class="document-content">
      {% block content %}{% endblock %}
    </div>

    {% block footer-wrapper %}
      <footer class="hidden-print">
        {% block footer-top %}{% endblock %}
        {% block footer %}
          <div class="document-footer">
            <div class="container-fluid">
              <div class="row">
                <p class="copyright col-sm-6">
                  Copyright 2015-{% now "Y" %}
                  <a href="http://www.psu.edu">The Pennsylvania State University</a>.
                  All Rights Reserved.
                </p>
                <p class="ownership col-sm-6">
                  Developed by the
                  <a href="http://equity.psu.edu"
                     >Office of the Vice Provost for Educational Equity</a>
                </p>
              </div>
            </div>
          </div>
        {% endblock %}
        {% block footer-bottom %}{% endblock %}
      </footer>
    {% endblock footer-wrapper %}

    {% block dialogs %}
    {% endblock dialogs %}

    {% block site-scripts %}
      <script type="text/javascript"
              src="{% static 'datalocker/js/jquery-2.1.4.min.js' %}"></script>
      <script type="text/javascript"
              src="{% static 'datalocker/js/bootstrap-3.3.5.min.js' %}"></script>
      <script type="text/javascript"
              src="{% static 'datalocker/js/moment-2.10.3.min.js' %}"></script>
    {% endblock site-scripts %}
  </body>
</html>

datalocker/templates/datalocker/pagination_template.html
{# Copyright 2015 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved. #}

{% comment %}
  Generic template for submission pagination

  Intended for use with the submission_view.html template
{% endcomment %}

  <a class="btn btn-default {% if newest_disabled %}disabled{% endif %}"
     role="group"
     aria-label="newest submission"
     title="Newest submission"
     href="{% url 'datalocker:submission_view' submission.locker.id newest.id %}">
    <span class="glyphicon glyphicon-fast-backward" aria-hidden="true"></span>
  </a>
  <a class="btn btn-default {% if newer_disabled %}disabled{% endif %}"
     role="group"
     aria-label="next submission"
     title="Newer submission"
     href="{% url 'datalocker:submission_view' submission.locker.id newer.id %}">
    <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
  </a>
  <a class="btn btn-default {% if older_disabled %}disabled{% endif %}"
     role="group"
     aria-label="last submission"
     title="Older submission"
     href="{% url 'datalocker:submission_view' submission.locker.id older.id %}">
    <span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
  </a>
  <a class="btn btn-default {% if oldest_disabled %}disabled{% endif %}"
     role="group"
     aria-label="oldest submission"
     title="Oldest submission"
     href="{% url 'datalocker:submission_view' submission.locker.id oldest.id %}">
    <span class="glyphicon glyphicon-fast-forward" aria-hidden="true"></span>
  </a>

datalocker/templates/datalocker/personalbar-menu-base.html
{# Copyright 2021 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved. #}

{% if user.is_staff %}
  <li role="presentation"
    ><a role="menuitem"
        tabindex="-1"
        href="{% url 'admin:index' %}"
      >Settings</a>
  </li>
  <li role="separator" class="divider"></li>
{% endif %}

{% block menuitem-password-change %}
  <li role="presentation"
    ><a role="menuitem"
        tabindex="-1"
        href="{% url 'datalocker:password_change' %}"
      >Change Password</a>
  </li>
{% endblock menuitem-password-change %}
<li role="presentation"
  ><a role="menuitem"
      tabindex="-1"
      href="{% block logout-url %}{% url 'datalocker:app_logout' %}{% endblock %}"
    >{% block logout-label %}Log out{% endblock logout-label %}</a>
</li>

datalocker/templates/datalocker/submission_view.html
{# Copyright 2015 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved. #}
{% extends "datalocker/app_template.html" %}
{% load static %}
{% load datalocker_tags %}

{% block breadcrumb-trail %}
  <li>
    <a href="{% url 'datalocker:index' %}">
      <span class="sr-only">List of </span>My Lockers
    </a>
  </li>
  <li>
    <a href="{% url 'datalocker:submissions_list' submission.locker.id %}">
      All Submissions<span class="sr-only"> for {{ locker.name }}</span>
    </a>
  </li>
  <li class="active">
    <span class="sr-only">{{ locker.name }}</span> Submission
  </li>
{% endblock breadcrumb-trail %}

{% block page-meta-title %}Submission View{% endblock page-meta-title %}

{% block site-styles %}
  {{ block.super }}
  <link type="text/css" rel="stylesheet"
        href="{% static 'datalocker/css/user_colors.css' %}" />
{% endblock site-styles %}

{% block content %}
  <div class="container-fluid">
    <h1>{{ submission.locker.name }}</h1>

    <ul class="messages list-unstyled" id="user-messages">
        {% for msg in messages %}
          <li class="alert {{ msg.tags }}">{{ msg|safe }}</li>
        {% endfor %}
    </ul>

    <div class="row">
      <div class="col-md-{% if sidebar_enabled %}7{% else %}12{% endif %}">
        <div aria-label="submission navigation buttons"
             class="pagination hidden-print">
          {% include "datalocker/pagination_template.html" %}
        </div>

        <ul class="list-unstyled">
          <li class="key-value-pair">
            <div class="key">Submission Date</div>
            <div class="value">{{ submission.timestamp }}</div>
          </li>
          {% for key, item in data.items %}
            <li class="key-value-pair">
              <div class="key">{{ key }}</div>
              <div class="value">
                {% if item.type == "list" %}
                  <ul>
                    {% for value in item.value %}
                      <li>{{ value }}</li>
                    {% endfor %}
                  </ul>
                {% elif item.type == "dict" %}
                  <ul>
                    {% for question, answer in item.value.items %}
                      <li>
                        <div class="key">{{ question }}</div>
                        <div class="value">{{ answer }}</div>
                      </li>
                    {% endfor %}
                  </ul>
                {% elif item.type == "table" %}
                  <div class="table-responsive">
                    <table class="table table-striped table-hover">
                      {% if item.headings %}
                        <thead>
                          <tr>
                            {% for id, title in item.headings.items %}
                              <th>{{ title }}</th>
                            {% endfor %}
                          </tr>
                        </thead>
                      {% endif %}
                      <tbody>
                        {% for row in item.value %}
                          <tr>
                            {% for column_id, value in row.items %}
                              <td>{{ value }}</td>
                            {% endfor %}
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                {% else %}
                  {{ item.value|linebreaks }}
                {% endif %}
              </div>
            </li>
          {% endfor %}
        </ul>

        <div aria-label="submission navigation buttons"
             class="pagination hidden-print">
          {% include "datalocker/pagination_template.html" %}
        </div>
      </div>


      {% if sidebar_enabled %}
        <div class="col-md-5">
          {% if workflow_enabled %}
            <div class="panel panel-default panel-workflow">
              <div class="panel-heading">
                <div class="panel-title">Workflow</div>
              </div>
              <div class="panel-body">
                <div>
                  <div class="workflow-label">Current State:</div>
                  <div class="workflow-state js-workflow-current-state">{{ workflow_state }}</div>
                </div>
                {% if workflow_users_can_edit %}
                  <form action="{% url 'datalocker:workflow_modify' submission.locker.id submission.id %}"
                        class="hidden-print"
                        id="workflow_form"
                        method="POST">
                    {% csrf_token %}

                    <label for="workflow-state">Change the workflow state</label>
                    <select name="workflow-state"
                            id="workflow-state"
                            class="form-control">
                      <option selected="selected"
                              disabled="disabled"
                              value="0"
                              >Select a new workflow state</option>
                      {% for state in workflow_states %}
                        <option value="{{ state }}">{{ state }}</option>
                      {% endfor %}
                    </select>
                  </form>
                {% endif %}
              </div>
            </div>
          {% endif %}

          {% if discussion_enabled %}
            {% if discussion_users_have_access %}
              <div class="panel panel-default panel-discussion"
                   data-url="{% url 'datalocker:comments_list' submission.locker.id submission.pk %}">
                <div class="panel-heading" >
                  <div class="panel-title">Discussion</div>
                </div>
                <div class="panel-body">
                  <form action="{% url 'datalocker:comment_add' submission.locker.id submission.pk %}"
                        class="discussion-add hidden-print"
                        data-edit-url="{% url 'datalocker:comment_modify' submission.locker.id submission.pk %}"
                        method="post"
                        >
                    {% csrf_token %}

                    <div class="form-group">
                      <label for="comment-text" class="sr-only">
                        Comment on this submission
                      </label>
                      <textarea name="comment"
                                class="form-control"
                                id="comment-text"
                                placeholder="Say something about this submission"
                                ></textarea>
                    </div>

                    <input type="submit"
                           class="btn btn-sm btn-primary"
                           value="Post" />
                  </form>

                  <ul class="media-list discussion-tree"></ul>
                </div>
              </div>
            {% endif %}
          {% endif %}

        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}


{% block site-scripts %}
  {{ block.super }}
  <script type="text/javascript"
          src=" {% static 'datalocker/js/messages.js' %}"></script>
  <script type="text/javascript"
          src=" {% static 'datalocker/js/workflow.js' %}"></script>
  <script type="text/javascript"
          src="{% static 'datalocker/js/commenting.js' %}"></script>
{% endblock site-scripts %}

datalocker/templates/datalocker/submissions_list.html
{# Copyright 2015 The Pennsylvania State University. Office of the Vice Provost for Educational Equity. All Rights Reserved. #}
{% extends "datalocker/app_template.html" %}
{% load static %}

{% block breadcrumb-trail %}
  <li>
    <a href="{% url 'datalocker:index' %}">
      <span class="sr-only">List of </span>My Lockers
    </a>
  </li>
  <li class="active">All Submissions
    <span class="sr-only"> for {{ locker.name }}</span>
  </li>
{% endblock breadcrumb-trail %}

{% block page-meta-title %}Submissions{% endblock page-meta-title %}


{% block site-styles %}
  {{ block.super }}
  <link type="text/css" rel="stylesheet"
        href="{% static 'datalocker/css/bootstrap-toggle.min.css' %}" />
{% endblock site-styles %}

{% block content %}
  <div class="container-fluid">
    {% if allow_maintenance_mode %}
      <div class="pull-right">
        {% if perms.datalocker.add_manual_submission %}
          <button class="btn btn-xs btn-primary js-submission-add hidden-print"
                  data-target="#dialog-submission-manual"
                  data-toggle="modal"
                  title="Manually add a submission to the locker"
                  >Add submission</button>
          &nbsp;
        {% endif %}
        <div class="switch-toggle hidden-print">
          <input type="checkbox"
                 name="maintenance-mode-toggle"
                 data-size="mini"
                 data-toggle="toggle"
                 data-onstyle="success"
                 data-offstyle="danger"
                 data-on="Done editing"
                 data-off="Edit submissions" />
        </div>
      </div>
    {% endif %}
    <h1>{{ locker.name }}</h1>
    <ul class="messages list-unstyled" id="user-messages">
      {% for msg in messages %}
        <li class="alert {{ msg.tags }}">{{ msg|safe }}</li>
      {% endfor %}
      <li class="alert alert-warning warning-maintenance-mode">
        <strong>Note:</strong>
        <em>Deleted</em> submissions will be permanently removed automatically
        after {{ purge_days }} days.
      </li>
    </ul>
    <button class="btn btn-default btn-xs hidden-print"
            role="filter-results"
            type="button"
            >Select the fields to display in the table</button>
    <table class="table table-striped table-hover listing tablesorter"
           name="submission listing"
           id="submission-list"
           data-csrf-token="{{ csrf_token }}"
           data-locker-id="{{ locker.id }}"
           data-delete-url="{% url 'datalocker:submission_delete' locker.id 0 %}"
           data-undelete-url="{% url 'datalocker:submission_undelete' locker.id 0 %}"
           >
      <caption>Form Submissions</caption>
      <thead>
        {% for heading in column_headings %}
          <th>{{ heading }}</th>
        {% endfor %}
        <th class="record-actions sr-only">Delete Submissions</th>
      </thead>
      <tbody>
        {# This is getting submissions that were submitted to the locker #}
        {% for submission in data %}
          <tr class="{% if submission.2 %}is-deleted{% endif %}"
              data-id="{{submission.1 }}"
              data-purge-timestamp="{{ submission.3|date:'c' }}"
              >
            {% for value in submission.0 %}
              <td data-count="{{ forloop.counter0 }}">
                {% if forloop.counter0 in linkable_indices %}
                  <a class="link"
                     href="{% url 'datalocker:submission_view' locker.id submission.1 %}"
                     >{{ value }}</a>
                  <span class="label label-danger label-deleted" />
                {% else %}
                  {{ value }}
                {% endif %}
              </td>
            {% endfor %}
            <td class="record-actions">
              <button type="button"
                role="delete-submission"
                class="btn btn-xs btn-danger"
                >Delete</button>
              <button type="button"
                role="undelete-submission"
                class="btn btn-xs btn-success"
                >Undelete</button>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}


{% block dialogs %}
{# Modal for filtering out the data shown in the submission list #}
  <div aria-hidden="true"
       aria-labelledby="dialog-filter-results-title"
       class="modal fade"
       id="dialog-filter-results"
       role="dialog"
       tabindex="-1"
       >
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'datalocker:submissions_list' locker.id %}"
              method="POST"
              name="modalForm"
              >
          {% csrf_token %}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"
                id="dialog-filter-results-title"
                >Select the form fields to display below</h4>
          </div>
          <div class="modal-body">
            <div>
              <label class="select-all-checkbox">
                <input data-target="fields-list"
                       id="fields-select-all"
                       role="select-all"
                       type="checkbox"
                       />
                Select All
              </label>
            </div>
            <ul class="list-unstyled" id="fields-list">
              {% for field in fields_list %}
                <li>
                  <label>
                    <input class="checkbox-inputs"
                           id="{{ field|slugify }}"
                           name="{{ field|slugify }}"
                           type="checkbox"
                           {% if field in selected_fields %}
                             checked="checked"
                           {% endif %}
                           />
                    {{ field }}
                  </label>
                </li>
              {% endfor %}
            </ul>
          </div>
          <div class="modal-footer">
            <input class="btn btn-primary btn-sm pull-left"
                   type="submit"
                   value="Update"
                   />
            <input class="btn btn-default btn-sm pull-left"
                   data-dismiss="modal"
                   type="button"
                   value="Close"
                   />
          </div>
        </form>
      </div>
    </div>
  </div>


{# Modal for adding a manual submission #}
  <div aria-hidden="true"
       aria-labelledby="dialog-submission-manual-title"
       class="modal fade"
       id="dialog-submission-manual"
       role="dialog"
       tabindex="-1"
       >
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'datalocker:submission_add' locker.id %}"
              method="POST"
              >
          {% csrf_token %}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"
                id="dialog-submission-manual-title"
                >Manually add a submission to the locker</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label for="submission-json">
                Paste the submission data in JSON format
              </label>
              <textarea class="form-control"
                        id="submission-json"
                        name="json"
                        rows="15"
                        ></textarea>
            </div>
            {% if request.user.is_superuser %}
              <div class="form-group">
                <label for="submission-timestamp">
                  Timestamp of the submission
                  <small class="text-primary">(optional)</small>
                </label>
                <input class="form-control"
                       id="submission-timestamp"
                       name="timestamp"
                       type="text"
                       value=""
                       />
              </div>
              {% if locker.workflow_enabled %}
                <div class="form-group">
                  <label for="submission-workflow-state">
                    Workflow state
                    <small class="text-primary">(optional)</small>
                  </label>
                  <input class="form-control"
                         id="submission-workflow-state"
                         name="workflow-state"
                         type="text"
                         value=""
                         />
                </div>
              {% endif %}
            {% endif %}
          </div>
          <div class="modal-footer">
            <input class="btn btn-primary btn-sm pull-left"
                   type="submit"
                   value="Add"
                   />
            <input class="btn btn-default btn-sm pull-left"
                   data-dismiss="modal"
                   type="button"
                   value="Cancel"
                   />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}


{% block site-scripts %}
    {{ block.super }}
    <script type="text/javascript"
            src=" {% static 'datalocker/js/bootstrap-toggle.js' %}"></script>
    {% comment %}
    <script type="text/javascript"
            src=" {% static 'datalocker/js/tablesorter.js' %}"></script>
    {% endcomment %}
    <script type="text/javascript"
            src=" {% static 'datalocker/js/select-all.js' %}"></script>
    <script type="text/javascript"
            src=" {% static 'datalocker/js/submission.js' %}"></script>
{% endblock site-scripts %}